[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "php artisan migrate --force && php artisan config:clear && echo 'Starting server...' && php artisan serve --host=0.0.0.0 --port=$PORT"

[env]
APP_ENV = "production"
APP_DEBUG = "true"
LOG_CHANNEL = "stderr"
PORT = "8080"
