[build]
builder = "NIXPACKS"

[build.env]
NIXPACKS_PHP_VERSION = "8.2"

[deploy]
startCommand = "php artisan optimize:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=$PORT"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
